import { Sfx, fitIntegerScale, letterboxOffset, load, save, viewport } from '@maga/arcade-core';

type Stat = 'strength'|'agility'|'vitality'|'defense';
type Mode = 'create'|'hub'|'arena'|'shop'|'complete';
interface Gladiator { name:string; look:string; stats:Record<Stat,number>; hp:number; maxHp:number; gold:number; xp:number; level:number; weapon:number; armor:number; potions:number }
interface Opponent { name:string; hp:number; maxHp:number; strength:number; defense:number }
interface SaveData { gladiator:Gladiator; defeated:number }
const STATS:Stat[]=['strength','agility','vitality','defense'];
const opponents=[{name:'Tin Can Tim',hp:34,strength:6,defense:2},{name:'Baron Bonk',hp:48,strength:8,defense:4},{name:'The Sand Snorter',hp:62,strength:10,defense:5},{name:'Emperor’s Champion',hp:78,strength:12,defense:7}];
const items=[{name:'Bent Bronze Sword',kind:'weapon',price:22,gate:1,bonus:2},{name:'Lucky Sandals',kind:'armor',price:38,gate:2,bonus:3},{name:'Imperial Buckler',kind:'armor',price:65,gate:3,bonus:5}];
const stage=document.querySelector<HTMLCanvasElement>('#stage')!; const ctx=stage.getContext('2d')!; const hud=document.querySelector('#hud')!; const chrome=document.querySelector('#chrome')!; const actions=document.querySelector('#actions')!; const logEl=document.querySelector('#log')!; const sfx=new Sfx();
let mode:Mode='create', points=6, selectedLook='Scarlet', logLines=['Welcome, challenger.']; let defeated=0; let opponent:Opponent|null=null; let turn=0; let guarded=false; let saveData=load<SaveData|null>('swords-and-sandals','slot',null); let g:Gladiator=saveData?.gladiator ?? {name:'',look:selectedLook,stats:{strength:2,agility:2,vitality:2,defense:2},hp:30,maxHp:30,gold:0,xp:0,level:1,weapon:0,armor:0,potions:2};
function log(s:string){logLines=[s,...logLines].slice(0,8);logEl.innerHTML=logLines.map(x=>`<div>${x}</div>`).join('')}
function persist(){save('swords-and-sandals','slot',{gladiator:g,defeated} satisfies SaveData)}
function level(){g.level=1+Math.floor(g.xp/40);}
function render(){hud.innerHTML=`<span>${mode.toUpperCase()} · ${g.name||'Unnamed gladiator'}</span><span>HP ${g.hp}/${g.maxHp} · Gold ${g.gold} · XP ${g.xp} · Lv ${g.level}</span>`; chrome.innerHTML=''; actions.innerHTML=''; if(mode==='create') renderCreate(); else if(mode==='hub') renderHub(); else if(mode==='arena') renderArena(); else if(mode==='shop') renderShop(); else {chrome.innerHTML='<h1>V1 COMPLETE</h1><p>The short arena ladder is conquered. Your save remains safe.</p>'; addButton('Return to Hub',()=>{mode='hub';render()})} draw();}
function addButton(text:string,fn:()=>void,disabled=false){const b=document.createElement('button');b.textContent=text;b.disabled=disabled;b.onclick=()=>{sfx.preset('ui');fn()};actions.appendChild(b)}
function renderCreate(){chrome.innerHTML=`<h1>Create Gladiator</h1><p>Look preset: <b>${selectedLook}</b></p><div class="grid">${['Scarlet','Azure','Gold'].map(x=>`<button data-look="${x}">${x}</button>`).join('')}</div><p>Skill points remaining: <b>${points}</b></p><div class="grid">${STATS.map(k=>`<button data-stat="${k}">${k}: ${g.stats[k]} +</button>`).join('')}</div><input id="name" placeholder="Gladiator name" value="${g.name}">`;chrome.querySelectorAll<HTMLButtonElement>('[data-look]').forEach(b=>b.onclick=()=>{selectedLook=b.dataset.look!;g.look=selectedLook;render()});chrome.querySelectorAll<HTMLButtonElement>('[data-stat]').forEach(b=>b.onclick=()=>{const k=b.dataset.stat as Stat;if(points){g.stats[k]++;points--;g.maxHp=24+g.stats.vitality*4;g.hp=g.maxHp;render()}});addButton('Enter the Arena',()=>{g.name=(document.querySelector<HTMLInputElement>('#name')?.value||'Unnamed Gladiator').slice(0,24);g.maxHp=24+g.stats.vitality*4;g.hp=g.maxHp;mode='hub';persist();render()},points>0)}
function renderHub(){chrome.innerHTML=`<h1>Hub — ${g.look} ${g.name}</h1><p>INTERNAL watermark: native replica slice. Prepare for the next bout.</p><p>Weapon +${g.weapon} · Armor +${g.armor} · Potions ${g.potions}</p>`;addButton(defeated?'Next Opponent':'Start First Bout',startFight);addButton('Visit Smithy / Armory',()=>{mode='shop';render()})}
function renderArena(){if(!opponent)return;chrome.innerHTML=`<h1>Arena: ${opponent.name}</h1><p>Opponent HP ${opponent.hp}/${opponent.maxHp} · ${guarded?'Opponent is off-balance.':''}</p>`;addButton('Attack',()=>act('attack'));addButton('Special',()=>act('special'));addButton(`Potion (${g.potions})`,()=>act('potion'),g.potions<1||g.hp===g.maxHp);addButton('End Turn',()=>enemyTurn())}
function renderShop(){chrome.innerHTML='<h1>Smithy / Armory</h1><p>Buy one item, then return to the arena.</p><div class="grid">'+items.map((it,i)=>`<button data-item="${i}" ${g.level<it.gate||g.gold<it.price?'disabled':''}>${it.name}<br>${it.price} gold · level ${it.gate}</button>`).join('')+'</div>';chrome.querySelectorAll<HTMLButtonElement>('[data-item]').forEach(b=>b.onclick=()=>{const it=items[Number(b.dataset.item)];g.gold-=it.price;if(it.kind==='weapon')g.weapon=Math.max(g.weapon,it.bonus);else g.armor=Math.max(g.armor,it.bonus);persist();log(`Bought ${it.name}. The smith nods solemnly.`);render()});addButton('Back to Hub',()=>{mode='hub';render()})}
function startFight(){const o=opponents[Math.min(defeated,opponents.length-1)];opponent={...o,maxHp:o.hp};turn=0;guarded=false;mode='arena';log(`The crowd chants for ${o.name}.`);render()}
function act(kind:'attack'|'special'|'potion'){if(!opponent)return;if(kind==='potion'){g.potions--;g.hp=Math.min(g.maxHp,g.hp+12);log('Potion consumed. It tastes like heroic fruit.');enemyTurn();return}turn++;const bonus=g.weapon;const chance=0.55+g.stats.agility*.04;const hit=Math.random()<chance; if(!hit){log('Miss! Your sword demonstrates interpretive dance.');enemyTurn();return}const crit=Math.random()<0.08+g.stats.agility*.01;let damage=(kind==='special'?7:4)+g.stats.strength+bonus+(crit?5:0);damage=Math.max(1,damage-opponent.defense);opponent.hp=Math.max(0,opponent.hp-damage);guarded=kind==='special';sfx.preset(crit?'hit':'shoot');log(`${crit?'Critical bonk! ':'Hit! '}${opponent.name} takes ${damage}.`);if(opponent.hp===0){win();return}enemyTurn()}
function enemyTurn(){if(!opponent)return;const damage=Math.max(1,opponent.strength+Math.floor(Math.random()*3)-g.stats.defense-Math.floor(g.armor/2)-(guarded?3:0));guarded=false;g.hp=Math.max(0,g.hp-damage);log(`${opponent.name} replies with a theatrical thump for ${damage}.`);if(g.hp===0){log('Defeat! The healer drags you back to the hub.');g.hp=g.maxHp;mode='hub';persist()}render()}
function win(){if(!opponent)return;const reward=18+defeated*8;g.gold+=reward;g.xp+=22;level();defeated++;log(`Victory! Earned ${reward} gold and XP.`);g.hp=g.maxHp;persist();sfx.preset('pickup');mode=defeated>=opponents.length?'complete':'hub';render()}
function draw(){const vp=viewport();const scale=fitIntegerScale(800,420,vp);const off=letterboxOffset(800,420,scale,vp);ctx.clearRect(0,0,800,420);ctx.fillStyle='#30263f';ctx.fillRect(0,0,800,420);ctx.fillStyle='#4d3855';ctx.fillRect(0,300,800,120);ctx.fillStyle='#ffd166';ctx.font='28px monospace';ctx.fillText(mode==='arena'?'ARENA OF BONKS':'SWORDS & SANDALS',24,55);ctx.fillStyle='#e879f9';ctx.beginPath();ctx.arc(230,220,55,0,Math.PI*2);ctx.fill();ctx.fillStyle='#60a5fa';ctx.beginPath();ctx.arc(570,220,55,0,Math.PI*2);ctx.fill();void off}
(document.querySelector('#mute') as HTMLButtonElement).onclick=()=>{sfx.muted=!sfx.muted;(document.querySelector('#mute') as HTMLButtonElement).textContent=sfx.muted?'SOUND OFF':'SOUND ON'};
if(location.search.includes('debug')){(window as unknown as {__maga:unknown}).__maga={get mode(){return mode},get screen(){return mode},get gladiatorStats(){return {...g.stats}},get hp(){return g.hp},get gold(){return g.gold},get xp(){return g.xp},get level(){return g.level},get opponent(){return defeated},get opponentHp(){return opponent?.hp??0},get shop(){return items.map(x=>({...x}))},get savePresent(){return load<SaveData|null>('swords-and-sandals','slot',null)!==null}}}
render();
